export const REPORT_CREATE_REQUEST = 'REPORT_CREATE_REQUEST';
export const REPORT_CREATE_SUCCESS = 'REPORT_CREATE_SUCCESS';
export const REPORT_CREATE_FAIL = 'REPORT_CREATE_FAIL';

export const REPORT_FETCH_REQUEST = 'REPORT_FETCH_REQUEST';
export const REPORT_FETCH_SUCCESS = 'REPORT_FETCH_SUCCESS';
export const REPORT_FETCH_FAIL = 'REPORT_FETCH_FAIL';

export const REPORT_DETAILS_REQUEST = 'REPORT_DETAILS_REQUEST';
export const REPORT_DETAILS_SUCCESS = 'REPORT_DETAILS_SUCCESS';
export const REPORT_DETAILS_FAIL = 'REPORT_DETAILS_FAIL';

export const REPORT_UPDATE_REQUEST = 'REPORT_UPDATE_REQUEST';
export const REPORT_UPDATE_SUCCESS = 'REPORT_UPDATE_SUCCESS';
export const REPORT_UPDATE_FAIL = 'REPORT_UPDATE_FAIL';
export const REPORT_UPDATE_RESET = 'REPORT_UPDATE_RESET';

export const REPORT_DELETE_REQUEST = 'REPORT_DELETE_REQUEST';
export const REPORT_DELETE_SUCCESS = 'REPORT_DELETE_SUCCESS';
export const REPORT_DELETE_FAIL = 'REPORT_DELETE_FAIL';

export const REPORT_TO_BEING_PROCESSED_REQUEST =
  'REPORT_TO_BEING_PROCESSED_REQUEST';
export const REPORT_TO_BEING_PROCESSED_SUCCESS =
  'REPORT_TO_BEING_PROCESSED_SUCCESS';
export const REPORT_TO_BEING_PROCESSED_FAIL = 'REPORT_TO_BEING_PROCESSED_FAIL';
export const REPORT_TO_BEING_PROCESSED_RESET =
  'REPORT_TO_BEING_PROCESSED_RESET';

export const REPORT_TO_DONE_REQUEST = 'REPORT_TO_DONE_REQUEST';
export const REPORT_TO_DONE_SUCCESS = 'REPORT_TO_DONE_SUCCESS';
export const REPORT_TO_DONE_FAIL = 'REPORT_TO_DONE_FAIL';
export const REPORT_TO_DONE_RESET = 'REPORT_TO_DONE_RESET';

export const REPORT_CREATE_COMMENT_REQUEST = 'REPORT_CREATE_COMMENT_REQUEST';
export const REPORT_CREATE_COMMENT_SUCCESS = 'REPORT_CREATE_COMMENT_SUCCESS';
export const REPORT_CREATE_COMMENT_FAIL = 'REPORT_CREATE_COMMENT_FAIL';

export const REPORT_DELETE_COMMENT_REQUEST = 'REPORT_DELETE_COMMENT_REQUEST';
export const REPORT_DELETE_COMMENT_SUCCESS = 'REPORT_DELETE_COMMENT_SUCCESS';
export const REPORT_DELETE_COMMENT_FAIL = 'REPORT_DELETE_COMMENT_FAIL';
